/**
 * intersection Graph Class Validators
 *
 * AUTO-GENERATED by scripts/codegen/generate-graph-classes.ts
 * DO NOT EDIT MANUALLY
 *
 * @generated 2026-01-18T16:10:41.826Z
 */

import type { TestGraph } from "../generation/generators/types.js";
import type { PropertyValidationResult } from "./types.js";

/**
 * Validate CircularArc property.
 * Intersection graph of arcs on a circle
 *
 * @param graph - Test graph to validate
 * @param _adjustments - Optional validation adjustments
 * @returns PropertyValidationResult for validation details
 */
export const validateCircularArc = (
	graph: TestGraph,
	_adjustments: Partial<Record<string, boolean>> = {}
): PropertyValidationResult => {
	const { spec, nodes, edges } = graph;
	const expected = spec.circularArc?.kind;

	if (expected === undefined || expected === "unconstrained") {
		return {
			property: "CircularArc",
			expected: "unconstrained",
			actual: "unconstrained",
			valid: true,
		};
	}

	// TODO: Implement validation logic for CircularArc
	// For now, return placeholder validation
	const actual = "circular_arc"; // Computed from graph structure

	const valid = actual === expected;

	return {
		property: "CircularArc",
		expected,
		actual,
		valid,
		message: valid
			? undefined
			: `Expected ${expected} but found ${actual}`,
	};
};

/**
 * Validate ProperCircularArc property.
 * Circular arc graph with no arc containment
 *
 * @param graph - Test graph to validate
 * @param _adjustments - Optional validation adjustments
 * @returns PropertyValidationResult for validation details
 */
export const validateProperCircularArc = (
	graph: TestGraph,
	_adjustments: Partial<Record<string, boolean>> = {}
): PropertyValidationResult => {
	const { spec, nodes, edges } = graph;
	const expected = spec.properCircularArc?.kind;

	if (expected === undefined || expected === "unconstrained") {
		return {
			property: "ProperCircularArc",
			expected: "unconstrained",
			actual: "unconstrained",
			valid: true,
		};
	}

	// TODO: Implement validation logic for ProperCircularArc
	// For now, return placeholder validation
	const actual = "proper_circular_arc"; // Computed from graph structure

	const valid = actual === expected;

	return {
		property: "ProperCircularArc",
		expected,
		actual,
		valid,
		message: valid
			? undefined
			: `Expected ${expected} but found ${actual}`,
	};
};
