/**
 * perfect_variants Graph Class Validators
 *
 * AUTO-GENERATED by scripts/codegen/generate-graph-classes.ts
 * DO NOT EDIT MANUALLY
 */

import type { TestGraph } from "../generation/generators/types.js";
import type { PropertyValidationResult } from "./types.js";

/**
 * Validate Modular property.
 * Every module is trivial
 *
 * @param graph - Test graph to validate
 * @param _adjustments - Optional validation adjustments
 * @returns PropertyValidationResult for validation details
 */
export const validateModular = (
	graph: TestGraph,
	_adjustments: Partial<Record<string, boolean>> = {}
): PropertyValidationResult => {
	const { spec } = graph;
	const expected = spec.modular?.kind;

	if (expected === undefined || expected === "unconstrained") {
		return {
			property: "Modular",
			expected: "unconstrained",
			actual: "unconstrained",
			valid: true,
		};
	}

	// TODO: Implement validation logic for Modular
	// For now, return placeholder validation
	const actual = "modular"; // Computed from graph structure

	const valid = actual === expected;

	return {
		property: "Modular",
		expected,
		actual,
		valid,
		message: valid
			? undefined
			: `Expected ${expected} but found ${actual}`,
	};
};

/**
 * Validate Ptolemaic property.
 * Distance hereditary and chordal
 *
 * @param graph - Test graph to validate
 * @param _adjustments - Optional validation adjustments
 * @returns PropertyValidationResult for validation details
 */
export const validatePtolemaic = (
	graph: TestGraph,
	_adjustments: Partial<Record<string, boolean>> = {}
): PropertyValidationResult => {
	const { spec } = graph;
	const expected = spec.ptolemaic?.kind;

	if (expected === undefined || expected === "unconstrained") {
		return {
			property: "Ptolemaic",
			expected: "unconstrained",
			actual: "unconstrained",
			valid: true,
		};
	}

	// TODO: Implement validation logic for Ptolemaic
	// For now, return placeholder validation
	const actual = "ptolemaic"; // Computed from graph structure

	const valid = actual === expected;

	return {
		property: "Ptolemaic",
		expected,
		actual,
		valid,
		message: valid
			? undefined
			: `Expected ${expected} but found ${actual}`,
	};
};

/**
 * Validate QuasiLine property.
 * No induced gem, no co-gem
 *
 * @param graph - Test graph to validate
 * @param _adjustments - Optional validation adjustments
 * @returns PropertyValidationResult for validation details
 */
export const validateQuasiLine = (
	graph: TestGraph,
	_adjustments: Partial<Record<string, boolean>> = {}
): PropertyValidationResult => {
	const { spec } = graph;
	const expected = spec.quasiLine?.kind;

	if (expected === undefined || expected === "unconstrained") {
		return {
			property: "QuasiLine",
			expected: "unconstrained",
			actual: "unconstrained",
			valid: true,
		};
	}

	// TODO: Implement validation logic for QuasiLine
	// For now, return placeholder validation
	const actual = "quasi_line"; // Computed from graph structure

	const valid = actual === expected;

	return {
		property: "QuasiLine",
		expected,
		actual,
		valid,
		message: valid
			? undefined
			: `Expected ${expected} but found ${actual}`,
	};
};
