/**
 * probe Graph Class Validators
 *
 * AUTO-GENERATED by scripts/codegen/generate-graph-classes.ts
 * DO NOT EDIT MANUALLY
 *
 * @generated 2026-01-18T16:10:41.826Z
 */

import type { TestGraph } from "../generation/generators/types.js";
import type { PropertyValidationResult } from "./types.js";

/**
 * Validate ProbeChordal property.
 * Vertices partitioned into probes and non-probes, can add edges among non-probes to make chordal
 *
 * @param graph - Test graph to validate
 * @param _adjustments - Optional validation adjustments
 * @returns PropertyValidationResult for validation details
 */
export const validateProbeChordal = (
	graph: TestGraph,
	_adjustments: Partial<Record<string, boolean>> = {}
): PropertyValidationResult => {
	const { spec, nodes, edges } = graph;
	const expected = spec.probeChordal?.kind;

	if (expected === undefined || expected === "unconstrained") {
		return {
			property: "ProbeChordal",
			expected: "unconstrained",
			actual: "unconstrained",
			valid: true,
		};
	}

	// TODO: Implement validation logic for ProbeChordal
	// For now, return placeholder validation
	const actual = "probe_chordal"; // Computed from graph structure

	const valid = actual === expected;

	return {
		property: "ProbeChordal",
		expected,
		actual,
		valid,
		message: valid
			? undefined
			: `Expected ${expected} but found ${actual}`,
	};
};

/**
 * Validate ProbeInterval property.
 * Can add edges among non-probes to form interval graph
 *
 * @param graph - Test graph to validate
 * @param _adjustments - Optional validation adjustments
 * @returns PropertyValidationResult for validation details
 */
export const validateProbeInterval = (
	graph: TestGraph,
	_adjustments: Partial<Record<string, boolean>> = {}
): PropertyValidationResult => {
	const { spec, nodes, edges } = graph;
	const expected = spec.probeInterval?.kind;

	if (expected === undefined || expected === "unconstrained") {
		return {
			property: "ProbeInterval",
			expected: "unconstrained",
			actual: "unconstrained",
			valid: true,
		};
	}

	// TODO: Implement validation logic for ProbeInterval
	// For now, return placeholder validation
	const actual = "probe_interval"; // Computed from graph structure

	const valid = actual === expected;

	return {
		property: "ProbeInterval",
		expected,
		actual,
		valid,
		message: valid
			? undefined
			: `Expected ${expected} but found ${actual}`,
	};
};
