/**
 * width Graph Class Validators
 *
 * AUTO-GENERATED by scripts/codegen/generate-graph-classes.ts
 * DO NOT EDIT MANUALLY
 *
 * @generated 2026-01-18T16:10:41.827Z
 */

import type { TestGraph } from "../generation/generators/types.js";
import type { PropertyValidationResult } from "./types.js";

/**
 * Validate Pathwidth property.
 * Pathwidth at most k
 *
 * @param graph - Test graph to validate
 * @param _adjustments - Optional validation adjustments
 * @returns PropertyValidationResult for validation details
 */
export const validatePathwidth = (
	graph: TestGraph,
	_adjustments: Partial<Record<string, boolean>> = {}
): PropertyValidationResult => {
	const { spec, nodes: _nodes, edges: _edges } = graph;
	const expected = spec.pathwidth?.kind;

	if (expected === undefined || expected === "unconstrained") {
		return {
			property: "Pathwidth",
			expected: "unconstrained",
			actual: "unconstrained",
			valid: true,
		};
	}

	// TODO: Implement validation logic for Pathwidth
	// For now, return placeholder validation
	const actual = "pathwidth_bounded"; // Computed from graph structure

	const valid = actual === expected;

	return {
		property: "Pathwidth",
		expected,
		actual,
		valid,
		message: valid
			? undefined
			: `Expected ${expected} but found ${actual}`,
	};
};

/**
 * Validate Cliquewidth property.
 * Cliquewidth at most k
 *
 * @param graph - Test graph to validate
 * @param _adjustments - Optional validation adjustments
 * @returns PropertyValidationResult for validation details
 */
export const validateCliquewidth = (
	graph: TestGraph,
	_adjustments: Partial<Record<string, boolean>> = {}
): PropertyValidationResult => {
	const { spec, nodes: _nodes, edges: _edges } = graph;
	const expected = spec.cliquewidth?.kind;

	if (expected === undefined || expected === "unconstrained") {
		return {
			property: "Cliquewidth",
			expected: "unconstrained",
			actual: "unconstrained",
			valid: true,
		};
	}

	// TODO: Implement validation logic for Cliquewidth
	// For now, return placeholder validation
	const actual = "cliquewidth_bounded"; // Computed from graph structure

	const valid = actual === expected;

	return {
		property: "Cliquewidth",
		expected,
		actual,
		valid,
		message: valid
			? undefined
			: `Expected ${expected} but found ${actual}`,
	};
};
