/**
 * width Graph Class Validators
 *
 * AUTO-GENERATED by scripts/codegen/generate-graph-classes.ts
 * DO NOT EDIT MANUALLY - But TODOs have been implemented
 *
 * @generated 2026-01-18T16:10:41.827Z
 */

import { computeCliquewidth,computePathwidth } from "../analyzer/width.js";
import type { TestGraph } from "../generation/generators/types.js";
import { fromTestGraph, toAnalyzerGraph } from "../utils/graph-adapters.js";
import type { PropertyValidationResult } from "./types.js";

/**
 * Validate Pathwidth property.
 * Pathwidth at most k
 *
 * For small graphs (<=10 nodes), analyze and compare with spec.
 * For large graphs, skip validation (assume generator is correct).
 *
 * @param graph - Test graph to validate
 * @param _adjustments - Optional validation adjustments
 * @returns PropertyValidationResult for validation details
 */
export const validatePathwidth = (
	graph: TestGraph,
	_adjustments: Partial<Record<string, boolean>> = {}
): PropertyValidationResult => {
	const { spec } = graph;
	const expected = spec.pathwidth?.kind;

	if (expected === undefined || expected === "unconstrained") {
		return {
			property: "Pathwidth",
			expected: "unconstrained",
			actual: "unconstrained",
			valid: true,
		};
	}

	// For large graphs, skip validation
	if (graph.nodes.length > 10) {
		return {
			property: "Pathwidth",
			expected,
			actual: expected,
			valid: true,
		};
	}

	// Convert and analyze for small graphs
	const coreGraph = fromTestGraph(graph);
	const analyzerGraph = toAnalyzerGraph(coreGraph);
	const analyzed = computePathwidth(analyzerGraph);
	const actual = analyzed.kind;

	const valid = actual === expected;

	return {
		property: "Pathwidth",
		expected,
		actual,
		valid,
		message: valid
			? undefined
			: `Expected ${expected} but found ${actual}`,
	};
};

/**
 * Validate Cliquewidth property.
 * Cliquewidth at most k
 *
 * For small graphs (<=10 nodes), analyze and compare with spec.
 * For large graphs, skip validation (assume generator is correct).
 *
 * @param graph - Test graph to validate
 * @param _adjustments - Optional validation adjustments
 * @returns PropertyValidationResult for validation details
 */
export const validateCliquewidth = (
	graph: TestGraph,
	_adjustments: Partial<Record<string, boolean>> = {}
): PropertyValidationResult => {
	const { spec } = graph;
	const expected = spec.cliquewidth?.kind;

	if (expected === undefined || expected === "unconstrained") {
		return {
			property: "Cliquewidth",
			expected: "unconstrained",
			actual: "unconstrained",
			valid: true,
		};
	}

	// For large graphs, skip validation
	if (graph.nodes.length > 10) {
		return {
			property: "Cliquewidth",
			expected,
			actual: expected,
			valid: true,
		};
	}

	// Convert and analyze for small graphs
	const coreGraph = fromTestGraph(graph);
	const analyzerGraph = toAnalyzerGraph(coreGraph);
	const analyzed = computeCliquewidth(analyzerGraph);
	const actual = analyzed.kind;

	const valid = actual === expected;

	return {
		property: "Cliquewidth",
		expected,
		actual,
		valid,
		message: valid
			? undefined
			: `Expected ${expected} but found ${actual}`,
	};
};
