/**
 * probe Graph Class Analyzers
 *
 * AUTO-GENERATED by scripts/codegen/generate-graph-classes.ts
 * DO NOT EDIT MANUALLY
 *
 * @generated 2026-01-18T16:10:41.826Z
 */

import type {
	ProbeChordal,
	ProbeInterval
} from "../generation/spec/probe.js";
import type { AnalyzerGraph , ComputePolicy } from "./types.js";

/**
 * Compute ProbeChordal property from graph structure.
 * Vertices partitioned into probes and non-probes, can add edges among non-probes to make chordal
 *
 * @param g - Analyzer graph
 * @param _policy - Computation policy (unused in generated analyzers)
 * @returns ProbeChordal with computed value
 */
export const computeProbeChordal = (
	g: AnalyzerGraph,
	_policy: ComputePolicy
): ProbeChordal => {
	// TODO: Implement analysis logic for ProbeChordal
	// For now, return placeholder value

	// Example: Check for forbidden subgraph
	// const hasForbidden = checkForForbiddenSubgraph(g);
	// return hasForbidden ? { kind: "not_probe_chordal" } : { kind: "probe_chordal" };

	return { kind: "probe_chordal" };
};

/**
 * Compute ProbeInterval property from graph structure.
 * Can add edges among non-probes to form interval graph
 *
 * @param g - Analyzer graph
 * @param _policy - Computation policy (unused in generated analyzers)
 * @returns ProbeInterval with computed value
 */
export const computeProbeInterval = (
	g: AnalyzerGraph,
	_policy: ComputePolicy
): ProbeInterval => {
	// TODO: Implement analysis logic for ProbeInterval
	// For now, return placeholder value

	// Example: Check for forbidden subgraph
	// const hasForbidden = checkForForbiddenSubgraph(g);
	// return hasForbidden ? { kind: "not_probe_interval" } : { kind: "probe_interval" };

	return { kind: "probe_interval" };
};
