/**
 * probe Graph Class Generators
 *
 * AUTO-GENERATED by scripts/codegen/generate-graph-classes.ts
 * DO NOT EDIT MANUALLY
 *
 * @generated 2026-01-18T16:10:41.826Z
 */

import type { GraphSpec } from "../spec.js";
import type { SeededRandom,TestEdge,TestNode  } from "./types.js";

/**
 * Generate ProbeChordal edges.
 * Vertices partitioned into probes and non-probes, can add edges among non-probes to make chordal
 *
 * @param nodes - Graph nodes
 * @param edges - Edge list to populate
 * @param spec - Graph specification
 * @param rng - Seeded random number generator
 */
export const generateProbeChordalEdges = (
	nodes: TestNode[],
	edges: TestEdge[],
	spec: GraphSpec,
	rng: SeededRandom
): void => {
	if (spec.probeChordal?.kind !== "probe_chordal") {
		throw new Error("ProbeChordal generation requires probe_chordal spec");
	}

	// TODO: Implement generation logic for ProbeChordal
	// This is a placeholder that generates random edges
	// Replace with actual constructive algorithm

	const nodeCount = nodes.length;

	// Simple random edge generation (replace with actual algorithm)
	for (let index = 0; index < nodeCount; index++) {
		const index_ = (index + 1 + rng.integer(0, nodeCount - 2)) % nodeCount;
		if (index < index_ && rng.next() > 0.5) {
			edges.push({ source: nodes[index].id, target: nodes[index_].id });
		}
	}
};

/**
 * Generate ProbeInterval edges.
 * Can add edges among non-probes to form interval graph
 *
 * @param nodes - Graph nodes
 * @param edges - Edge list to populate
 * @param spec - Graph specification
 * @param rng - Seeded random number generator
 */
export const generateProbeIntervalEdges = (
	nodes: TestNode[],
	edges: TestEdge[],
	spec: GraphSpec,
	rng: SeededRandom
): void => {
	if (spec.probeInterval?.kind !== "probe_interval") {
		throw new Error("ProbeInterval generation requires probe_interval spec");
	}

	// TODO: Implement generation logic for ProbeInterval
	// This is a placeholder that generates random edges
	// Replace with actual constructive algorithm

	const nodeCount = nodes.length;

	// Simple random edge generation (replace with actual algorithm)
	for (let index = 0; index < nodeCount; index++) {
		const index_ = (index + 1 + rng.integer(0, nodeCount - 2)) % nodeCount;
		if (index < index_ && rng.next() > 0.5) {
			edges.push({ source: nodes[index].id, target: nodes[index_].id });
		}
	}
};
