/**
 * structural Graph Class Generators
 *
 * AUTO-GENERATED by scripts/codegen/generate-graph-classes.ts
 * DO NOT EDIT MANUALLY
 *
 * @generated 2026-01-18T16:10:41.828Z
 */


// Skipped: WeaklyChordal (property already exists or was renamed)
