/**
 * forbidden_subgraph Graph Class Type Definitions
 *
 * AUTO-GENERATED by scripts/codegen/generate-graph-classes.ts
 * DO NOT EDIT MANUALLY
 *
 * @generated 2026-01-18T16:10:41.823Z
 */

/**
 * Contains no induced path on 5 vertices
 */
export type P5Free = { kind: "p5_free" } | { kind: "has_p5" } | { kind: "unconstrained" };

/**
 * Contains no induced cycle on 5 vertices
 */
export type C5Free = { kind: "c5_free" } | { kind: "has_c5" } | { kind: "unconstrained" };

/**
 * Contains no induced bull graph
 */
export type BullFree = { kind: "bull_free" } | { kind: "has_bull" } | { kind: "unconstrained" };

/**
 * Contains no induced gem graph
 */
export type GemFree = { kind: "gem_free" } | { kind: "has_gem" } | { kind: "unconstrained" };

/**
 * No hole or antihole of length 5 or more
 */
export type WeaklyChordal = { kind: "weakly_chordal" } | { kind: "has_hole_or_antihole" } | { kind: "unconstrained" };

/**
 * No asteroidal triple of vertices
 */
export type ATFree = { kind: "at_free" } | { kind: "has_asteroidal_triple" } | { kind: "unconstrained" };

/**
 * No induced house or hole
 */
export type HHFree = { kind: "hh_free" } | { kind: "has_house_or_hole" } | { kind: "unconstrained" };

/**
 * Distances preserved in all connected induced subgraphs
 */
export type DistanceHereditary = { kind: "distance_hereditary" } | { kind: "not_distance_hereditary" } | { kind: "unconstrained" };
