/**
 * geometric Graph Class Type Definitions
 *
 * AUTO-GENERATED by scripts/codegen/generate-graph-classes.ts
 * DO NOT EDIT MANUALLY
 *
 * @generated 2026-01-18T16:10:41.827Z
 */

/**
 * Can be drawn in plane without edge crossings
 */
export type Planar = { kind: "planar" } | { kind: "nonplanar" } | { kind: "unconstrained" };

/**
 * Backward compatibility alias for Planar
 * @deprecated Use Planar instead
 */
export type Planarity = { kind: "planar" } | { kind: "non_planar" } | { kind: "unconstrained" };

/**
 * Unit disk graph property
 * Graph formed by unit disks in the plane
 */
export type UnitDisk =
  | { kind: "unit_disk"; unitRadius?: number; spaceSize?: number }
  | { kind: "not_unit_disk" }
  | { kind: "unconstrained" };
