/**
 * intersection Graph Class Type Definitions
 *
 * AUTO-GENERATED by scripts/codegen/generate-graph-classes.ts
 * DO NOT EDIT MANUALLY
 *
 * @generated 2026-01-18T16:10:41.825Z
 */

/**
 * Intersection graph of arcs on a circle
 */
export type CircularArc = { kind: "circular_arc" } | { kind: "not_circular_arc" } | { kind: "unconstrained" };

/**
 * Circular arc graph with no arc containment
 */
export type ProperCircularArc = { kind: "proper_circular_arc" } | { kind: "not_proper_circular_arc" } | { kind: "unconstrained" };

/**
 * Intersection graph of disks in the plane
 */
export type Disk = { kind: "disk" } | { kind: "not_disk" } | { kind: "unconstrained" };

/**
 * Intersection graph of unit disks in the plane
 */
export type UnitDisk = { kind: "unit_disk" } | { kind: "not_unit_disk" } | { kind: "unconstrained" };
