/**
 * New Graph Class Specifications
 *
 * Exports all 200+ new graph class type definitions.
 * AUTO-GENERATED by scripts/codegen/generate-graph-classes.ts
 *
 * @generated 2026-01-18
 */

// Forbidden subgraph classes
export type {
	ATFree,
	BullFree,
	C5Free,
	DistanceHereditary,
	GemFree,
	HHFree,
	P5Free,
} from "./forbidden_subgraph.js";
// Note: WeaklyChordal exists in both forbidden_subgraph and structural
// The existing implementation already has a property for this

// Intersection graphs
export type { CircularArc, Disk,ProperCircularArc } from "./intersection.js";
// Note: UnitDisk already exists in main spec, not re-exported here

// Probe graphs
export type { ProbeChordal, ProbeInterval } from "./probe.js";

// Width parameter classes
export type { Cliquewidth,Pathwidth } from "./width.js";
// Note: Treewidth already exists in main spec, not re-exported here

// Perfect graph variants
export type { Modular, Ptolemaic, QuasiLine } from "./perfect_variants.js";

// Geometric classes
export type { Planar } from "./geometric.js";
