/**
 * perfect_variants Graph Class Type Definitions
 *
 * AUTO-GENERATED by scripts/codegen/generate-graph-classes.ts
 * DO NOT EDIT MANUALLY
 *
 * @generated 2026-01-18T16:10:41.827Z
 */

/**
 * Every module is trivial
 */
export type Modular = { kind: "modular" } | { kind: "not_modular" } | { kind: "unconstrained" };

/**
 * Distance hereditary and chordal
 */
export type Ptolemaic = { kind: "ptolemaic" } | { kind: "not_ptolemaic" } | { kind: "unconstrained" };

/**
 * No induced gem, no co-gem
 */
export type QuasiLine = { kind: "quasi_line" } | { kind: "not_quasi_line" } | { kind: "unconstrained" };
