/**
 * probe Graph Class Type Definitions
 *
 * AUTO-GENERATED by scripts/codegen/generate-graph-classes.ts
 * DO NOT EDIT MANUALLY
 *
 * @generated 2026-01-18T16:10:41.826Z
 */

/**
 * Vertices partitioned into probes and non-probes, can add edges among non-probes to make chordal
 */
export type ProbeChordal = { kind: "probe_chordal" } | { kind: "not_probe_chordal" } | { kind: "unconstrained" };

/**
 * Can add edges among non-probes to form interval graph
 */
export type ProbeInterval = { kind: "probe_interval" } | { kind: "not_probe_interval" } | { kind: "unconstrained" };
