/**
 * width Graph Class Type Definitions
 *
 * AUTO-GENERATED by scripts/codegen/generate-graph-classes.ts
 * DO NOT EDIT MANUALLY
 *
 * @generated 2026-01-18T16:10:41.826Z
 */

/**
 * Pathwidth at most k
 */
export type Pathwidth = { kind: "pathwidth_bounded" } | { kind: "pathwidth_unbounded" } | { kind: "unconstrained" };

/**
 * Cliquewidth at most k
 */
export type Cliquewidth = { kind: "cliquewidth_bounded" } | { kind: "cliquewidth_unbounded" } | { kind: "unconstrained" };
